#!/bin/sh

module=thermometer
device=thermometer
mode="664"
set -e
# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

case "$1" in
    start)
        modprobe ${module} || exit 1
        major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
        rm -f /dev/${device}
        mknod /dev/${device} c $major 0
        chgrp $group /dev/${device}
        chmod $mode  /dev/${device}
        ;;
    stop)
        rmmod $module || exit 1
        rm -f /dev/${device}
        ;;
    *)
        echo "invalid argument"
        exit 1
        ;;
esac

exit 0
