name: Build Image
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Create Raspberry Pi image
        uses: Enchan1207/rpi-buildroot@v1
        with:
          github_token: ${{ secrets.SSH_PRIVATE_KEY }}
          config_file: './base_external/configs/thermometer_rpi0_defconfig'

      - uses: actions/upload-artifact@v4
        with:
          name: raspberry pi image
          path: sdcard.img
